###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    php-fpm:
      image: php:7.2.27-fpm-buster
      container_name: test-php-fpm
      working_dir: /application
      volumes:
        - .:/application